### ISSUE TITLE
Problems with the release packaging

### ISSUE THREAD

**Issue by christian-byrne** [googincheng/ComfyUX#11]
1 - Unzipping the latest release creates a `__MACOSX` dir in `custom_nodes` which Comfy tries to load as its own custom node. Using the `UnZip` utility (linux). 

<details>
<summary> Terminal output </summary>

```
Total VRAM 11975 MB, total RAM 31906 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /home/c_byrne/projects/comfy-testing-environment/ComfyUI/web
😊 ComfyUX.py hello world
😊ComfyUXServer setup
<StaticResource 'ComfyUXStatic' /ComfyUXStatic -> PosixPath('/home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/ComfyUX-release/WebExtension')>
Traceback (most recent call last):
  File "/home/c_byrne/projects/comfy-testing-environment/ComfyUI/nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/__MACOSX/__init__.py'

Cannot import /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/__MACOSX module for custom nodes: [Errno 2] No such file or directory: '/home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/__MACOSX/__init__.py'

Import times for custom nodes:
   0.0 seconds: /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/__MACOSX
   0.0 seconds: /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/ComfyUX-release

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

</details>

2 - Downloading the source code version of the release creates a dir with a `.` in its name, which can't be loaded as a python module.

<details>
<summary> Terminal output </summary>

```
Traceback (most recent call last):
  File "/home/c_byrne/projects/comfy-testing-environment/ComfyUI/nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/ComfyUX-0.6.0/__init__.py", line 1, in <module>
    from .PyComfyNode.ComfyUX import ComfyUX
ModuleNotFoundError: No module named 'ComfyUX-0'

Cannot import /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/ComfyUX-0.6.0 module for custom nodes: No module named 'ComfyUX-0'

Import times for custom nodes:
   0.0 seconds: /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/prompt-cli
   0.0 seconds (IMPORT FAILED): /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/ComfyUX-0.6.0
   0.5 seconds: /home/c_byrne/projects/comfy-testing-environment/ComfyUI/custom_nodes/audio-tools

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

</details>

**Comment by googincheng** [comment]
Thks for the detatil terminal log. Seems the .DS_Store and */__pycache folder cause the problem, I have cleaned it.

Latest release update:
https://github.com/googincheng/ComfyUX/releases/tag/v0.6.0

Main branch commit:
[Delete .DS_Store](https://github.com/googincheng/ComfyUX/commit/104d77a2814d2027f9ef21c9ddf9d1c106a32563)

**Comment by christian-byrne** [comment]
Thanks! The `__MACOSX` folder is still in the zip file. To avoid that you probably need to use command line to make the zip instead of Mac builtin tool.

**Comment by googincheng** [comment]
Nice suggestion, it works!
